### ISSUE TITLE
Joplin helm chart - Can't choose a storageClass, when using persistent storage

### ISSUE THREAD

**Issue by peterweissdk** [RubxKube/charts#280]
When i deploy the chart with persistent storage enabled for Postgres, and choosing a storageClass, the installation sets the storageClass to the default storageClass (Longhorn) for my K8s setup.

The storageClass is a nfs mount, and i have other installations using it.

Here is a snippet of my values file:
```yaml
postgresql:
  enabled: true
  auth:
    postgresPassword: "postgressPsswd"
    database: joplin
    username: johndoe
    password: passwd
  persistence:
    enabled: true
    existingClaim: ""
    storageClass: "nfs-csi"
    size: 8Gi 
```

**Comment by peterweissdk** [comment]
I see that I didn't get the right yaml syntax pasted in the textbox above, but the textbox removes the spaces from beginning of every line, when i post the issue!!!!
The chart installs without any errors, so i don't think it is a yaml syntax problem.

**Comment by qjoly** [comment]
Hey, 

I released a new version of joplin 😄 You can try to update to [1.2.0](https://github.com/RubxKube/charts/releases/tag/joplin-1.2.0). I had to edit the values to match the Bitnami postgresql chart : 

```yaml
postgresql:
  enabled: true
  auth:
    postgresPassword: "changeme"
    database: joplin
    username: joplinuser
    password: joplinpass
  primary:
    persistence:
      enabled: true
      existingClaim: ""
      storageClass: ""
      # size: 8Gi
```

ps: I edited your issue to add the blockquote
